### ISSUE TITLE
6.2 model house table

### ISSUE THREAD

**Issue by maheshnimbal** [salujajaskeerat/ELP305-TribeD-documentation#1]
![image](https://user-images.githubusercontent.com/67149319/151985840-4556cd39-d26f-4ffe-b3af-dc423db286fc.png)
Don't write for a fridge etc.

![image](https://user-images.githubusercontent.com/67149319/151985977-f32664ba-3197-4fed-9782-080466299125.png)
this is what sir expects

**Comment by salujajaskeerat** [comment]
"15A 3pin power outlet" is now used in the docs.
Let me know if something similar is missed .
reopen the issue if you find similar mistake
